name: Deploy
on: [push]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    permissions:
      id-token: write # Needed for auth with Deno Deploy
      contents: read # Needed to clone the repository

    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: npm-${{ hashFiles('package-lock.json') }}
          restore-keys: npm-

      - name: Install dependencies
        run: npm ci --ignore-scripts

      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Build client
        run: deno run --allow-run --allow-read --allow-env src/chat/buildClient.ts

      - name: Upload to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: "liveviewjs-deno-chat"
          entrypoint: "./src/chat/index.ts"
